# hash:sha256:d232b32f7ce950c0bd88042bebd0968c4526c715e312163bca743e7781b22060
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/omix-r-statistics:r4.4.3-bioconductor3.20-v1

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-ask-pass /
